### ISSUE TITLE
Not processing emails that aren't whitelisted

### ISSUE THREAD

**Issue by karanrajpal14** [danielireson/formplug#20]
I'd like to reference #19 but have this as a separate issue in-case someone has the same problem. I did follow your suggestion and added the header but I still seem to be facing issues.

Firstly, here's the curl call that I am using:
```curl --location --request POST 'https://hgwaf31jxa.execute-api.us-west-2.amazonaws.com/dev/?format=json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode '_to=rajpal.karan73@gmail.com' \
--data-urlencode 'message=test' \
--data-urlencode 'name=test' \
--data-urlencode 'email=test'
```

This throws an error stating that I have not whitelisted this particular email. Well, the documentation states that "Whitelisted Recipients" are not required. Which is why I've chosen to leave them blank. Here's what my `config.json` looks like:
```
{
  "SERVICE_NAME": "karanr-form-backend",
  "ENCRYPTION_KEY": "<key>",
  "REGION": "us-west-2",
  "STAGE": "dev",
  "SENDER_ARN": "<arn>",
  "WHITELISTED_RECIPIENTS": []
}
```

But, when I do make the call, I get an error saying:
```
{
    "statusCode": 422,
    "message": "Non-whitelisted email in '_to' field"
}
```

Also, I did try adding in my email to the whitelist like so:
```
{
  "SERVICE_NAME": "karanr-form-backend",
  "ENCRYPTION_KEY": "<key>",
  "REGION": "us-west-2",
  "STAGE": "dev",
  "SENDER_ARN": "<arn>",
  "WHITELISTED_RECIPIENTS": ["rajpal.karan73@gmail.com"]
}
```

But, to no avail. I then get an error like so:
```
{
    "statusCode": 500,
    "message": "An unexpected error occurred"
}
```

Do you have any idea what's going wrong? Any suggestions?

**Comment by hpawe01** [comment]
I had also some problems and had to look at the AWS Lambda CloudWatch Insight Log to figure out the specific error, because "An unexpected error occurred" is not that helpful.

My first error was, that I used the wrong `SENDER_ARN` (not the one from a whitelisted E-Mail address from AWS SES).
And the second error was, that I didn't had permission (in AWS Lambda) to send emails to the `_to` address, although I verified it (as described in the `README.md`). I fixed it by adding it explicitly to the `serverless.yml` as additional `iamRoleStatement`:
```
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ${file(config.json):RECIPIENT_ARN}
```

Hope that helps.

**Comment by Kulcanhez** [comment]
Hello @danielireson @hpawe01 🙂. I'm new to AWS and I'm trying to put this amazing serverless working. Hopefully, you can help me. First of all, thank you for your work and support.

I'm having `An unexpected error occurred`. I checked the Cloudwatch logs and I have this weird error:
![cloudwatch](https://user-images.githubusercontent.com/5109593/83859108-62aedc00-a715-11ea-8066-f0f5c8d5a2b8.jpg)

Here is my `config.json`:
![configjson](https://user-images.githubusercontent.com/5109593/83859233-870ab880-a715-11ea-9570-4f134a380f55.png)

Here is part of my `serverless.yml`:
![serverless](https://user-images.githubusercontent.com/5109593/83859281-95f16b00-a715-11ea-8206-b3ac90b0d391.png)

And here is my completely simple contact form:
![contactform](https://user-images.githubusercontent.com/5109593/83860722-8f63f300-a717-11ea-8c10-c9ba339ec0d0.png)

The `SENDER_ARN` is the same as the whitelist email that I'm using.

I also tried adding the same `RECIPIENT_ARN` to see if it solves but nothing.

What I am doing wrong?

Really thank you for your help ❤️

**Comment by hpawe01** [comment]
I am only a beneficiary of this service created by @danielireson 

I don't see anything wrong with your configuration. In my ARNs the whole email address is behind the last `/` though and in your ARNs it looks like it is only the domain? So are you sure that you use the correct ARNs of the email addresses configured in SES?

**Comment by Kulcanhez** [comment]
> I am only a beneficiary of this service created by @danielireson
> 
> I don't see anything wrong with your configuration. In my ARNs the whole email address is behind the last `/` though and in your ARNs it looks like it is only the domain? So are you sure that you use the correct ARNs of the email addresses configured in SES?

You're amazing!! ❤️ I was using domain ARN instead of email ARN. Now it's working.

However, I have this last issue. I have the hidden `_to` for the email I want to receive (info@example.com) and the `_replyTo` for the visitor email. In the whitelist, I have my email (info@example.com).

But now Formplug is verifying `_replyTo` if it is whitelisted `Non-whitelisted email in '_replyTo' field. How are you doing for your visitors to insert their email?

```
<input type="email" name="_replyTo" required />
<input type="text" name="message" required />
<input type="hidden" name="_to" value="info@example.com" />
```

Thank you!! 🙂

**Comment by hpawe01** [comment]
Glad I could help. I don't use this `_replyTo` field so I don't know how this should work. Maybe @danielireson or someone else can help with this question.

**Comment by Kulcanhez** [comment]
Fixed by commenting this code on Request.js 😃 Thank you all!!
![Screenshot 2020-06-11 at 14 55 04](https://user-images.githubusercontent.com/5109593/84393519-95fcd980-abf3-11ea-90e9-04bd01e3ce9e.jpg)

**Comment by danielireson** [comment]
I'm going to close this as workarounds have been suggested.

It looks like there were a few different issues mentioned in this thread:
- The configuration for `WHITELISTED_RECIPIENTS` was previously set to an empty array in `config.sample.json` by default. When creating `config.json` for your own deployment this value needed updating with whitelisted emails or removing. I've since changed the default so it's disabled to prevent this from happening.
- There were IAM issues and a suggested fix was to add an extra "sendEmail" permisssion to allow `RECIPIENT_ARN` to send emails. I'm struggling to understand how this would have fixed anything as a recipient doesn't need to send emails. I think the fix is more likely to have been a byproduct of redeploying the service with an updated config, the wrong ARN values being used initially, or perhaps there's a small time delay when leaving SES sandbox mode (i.e. a delay after the AWS support ticket was closed).
- There's a use-case for having non-whitelisted `_replyTo` emails but whitelisted `_to`/`_cc`/`_bcc` emails that I haven't considered. The workaround here is to either disable whitelisting or accept the visitors email as a separate field (e.g. "visitorEmail") and then compose a new email in your email client when you want to reply. This is definitely more cumbersome and if this comes up in the future I'll look at changing how this works.
